apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flipkart-ingress
  namespace: flipkart-staging
spec:
  rules:
  - host: stage-flipstore.elsondevops.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: staging-flipkart-app-service
            port:
              number: 80
