apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart-app
  template:
    metadata:
      labels:
        app: flipkart-app
    spec:
      containers:
      - name: app
        image: flipkart-app:IMAGE_TAG
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-service
spec:
  selector:
    app: flipkart-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
