apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../k8s-80

namePrefix: prod-
namespace: flipkart-prod

replicas:
- name: flipkart-app-deployment
  count: 3

images:
- name: 739275449845.dkr.ecr.us-east-1.amazonaws.com/flipkartimg
  newTag: latest

patchesStrategicMerge:
- ingress-patch.yaml
